set hlsearch " highlight the search
set mouse=a " allows to use the mouse in all modes
set cindent " indent
set wildmenu " Menu for auto completation
set cursorline " Line over the current position
set autoread " Automatically update the files if an external change occurs
set encoding=utf-8 " Set defult encoding to utf-8
set fileencoding=utf-8 " Set defult encoding to utf-8

" indentation with 4 spaces
set tabstop=4
set shiftwidth=4
set expandtab

" Dont create extra file
set noswapfile
set nobackup
set nowb

syntax on " Set colors

so ~/Github/Configurations/Vim/VimPlugin/Main.vim " commands
so ~/Github/Configurations/Vim/VimPlugin/Scheme.vim " theme

match WhiteSpace /\s\+$/ " highlight the unwanted spaces
                         " \s whitespaces
                         " \+ match more than one
                         " $ until end of line

match TabLine /\s\t/ " highlight tabs

set colorcolumn=81
highlight ColorColumn ctermbg=4
