set hlsearch " highlight the search
set mouse=a " allows to use the mouse in all modes
set cindent " indent
set wildmenu " Menu for auto completation
set cursorline " Line over the current position
set autoread " Automatically update the files if an external change occurs
set tabstop=4 " set tab as 4 spaces
set expandtab " take tabs as spaces

" indentation with 4 spaces
set shiftwidth=4
set softtabstop=4

" Dont create extra file
set noswapfile
set nobackup
set nowb

set shellcmdflag=-ic " Allow aliases from vim
syntax on " Set colors

so ~/Github/Vim/VimPlugin/Main.vim " commands
so ~/Github/Vim/VimPlugin/Scheme.vim " theme

match WhiteSpace /\s\+$/ " highlight the unwanted spaces
