command W execute "!run %"
command T execute "tabnew"

let name = expand('%:r')

au BufNewFile *.java exe "normal Opublic class"name "{\n\n public static void main(String[] args){\n" name tolower(name) "= new"name."()".";\n}\n}\<Esc>gg"

set cindent
set hlsearch
set mouse=a

set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

set tabstop=4 

set wildmenu "El mejor menu que existe
set cursorline

set autoread "cambia autamaticamente si el archivo es modificado de afuera
			 
set noswapfile "no crea .swp
set nobackup "no hace backup
set nowb 

set shellcmdflag=-ic "deja utilizar ALIAS!

syntax on
color zellner
