RS="\[\033[0m\]"    # reset
HC="\[\033[1m\]"    # hicolor
FYEL="\[\033[33m\]" # foreground yellow
FBLE="\[\033[34m\]" # foreground blue

PS1="${HC}${FBLE}you are in \w $FYEL-> $RS"

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
