source /home/alejandro/Github/ResRst/script.sh
source /home/alejandro/Dropbox/Universidad/Compiladores/lexer_st0270/Test.sh
alias antlr4="java -jar /home/alejandro/Dropbox/Universidad/Compiladores/InfoPractica/antlr-4.5-complete.jar"
alias comp="open /home/alejandro/Dropbox/Universidad/Compiladores/InfoPractica/ST0270-2015-1-Practica-02.pdf"
alias abook="open /home/alejandro/Dropbox/Universidad/Compiladores/InfoPractica/Antlr4.pdf"
alias gram="open /home/alejandro/Dropbox/Universidad/Compiladores/InfoPractica/Gramatica.pdf"

# Alias for i3
alias shoot="import -window root screenshot.jpg"

# Alias to manage the latex compilation
alias lpdf="pdflatex"
alias cpdf="rm -f *.out *.dvi *.blg *.bbl *.aux *.log"
alias cdiap="rm -f *.nav *.out *.snm *.toc *.aux *.log"
alias dvi="xdvi"

# Aliases to shorten linux commands
alias x="exit"
alias open="gnome-open"
alias k="killall"
alias deb="sudo dpkg -i"
alias msg="notify-send"
alias rf="rm -r"
# alias rm="rm -i"       # Uncomment to activate the interactive mode of rm
alias moo="apt-get moo"  # Prints a cow on the terminal
alias put="banner"
alias bin="xxd -b"       # Prints the binary representation of a file
alias untar="tar zxvf"
alias exe="chmod u+x"

# Aliases to open programs
alias vilist="VBoxManage list runningvms"
alias master="VBoxManage startvm Master --type headless &"
alias slaves="(VBoxManage startvm Slave2 --type headless &) ; (VBoxManage startvm Slave1 --type headless &)"
alias viconnect="ssh root@127.0.0.1 -p 2222"

# Prints doge on the terminal
alias doge="~/Github/Bash/doge.sh"

# Functions

find2(){
    find . -iname $1
}

multi(){
    if [ -z $1 ]; then
        xrandr --auto
    else
        xrandr --output VGA1 --auto --$1-of LVDS1
    fi
}

get(){
    history | grep $1
}

refresh(){
    source ~/.bash_aliases
    echo Done
}

mkjar(){
        fl=$1 && javac $1 && echo Main-Class: ${fl/.java/""} > MANIFEST.MF && jar -cvmf MANIFEST.MF ${fl/.java/.jar} ${fl/.java/.class}
        rm -f ${program/.java/.class} MANIFEST.MF
}

run(){
	program=$1
    javac $1
    if [ $? -eq 0 ]; then
        if [ -z $2 ]; then
            java ${program/.java/""}
        else
            java ${program/.java/""} ${*:2}
        fi
    fi

    rm -f *.class
}

hrun(){
    program=$1
    ghc $1
    if [ $? -eq 0 ]; then
        echo ""
        ./${program/.hs/""}
    fi

    rm -f *.hi *.o ${program/.hs/""}
}

pdfbib(){
	archivo=$1;
    latex $1
    if [ $? -eq 0 ]; then
        bibtex ${archivo/.tex/.aux}
        latex $1
        latex $1
        lpdf $1
        cpdf
        open ${archivo/.tex/".pdf"}
    fi
}

pdf(){
	archivo=$1;
    pdflatex $1
    if [ $? -eq 0 ]; then
        cpdf
        open ${archivo/.tex/".pdf"}
    fi
}

diap(){
    lpdf $1 && cdiap && archivo=$1 && open ${archivo/.tex/.pdf}
}
